### ISSUE TITLE
regarding fonts

### ISSUE THREAD

**Issue by mingyue2108** [HIllya51/Cartagra_FHD_CHS#16]
Hello, sir.
May I ask a question about creating CZ2 fonts?
I attempted to run getcharsetv4.py, and it requires some info* _string_sort_utf-8.txt files.
But I don't know where to get them.
Thank you.

**Comment by HIllya51** [comment]
You can see at line 126: os.system(rf'.\LucaSystemTool\LucaSystemTools.exe -t info -m export -f "C:\InnocentGrey\カルタグラ FHD\files\FONT\info{size}"  ')
It will generate both like "info11_dicStr_sort2.txt" and "info11_string_sort_utf-8.txt". You can manually generate those "info* _string_sort_utf-8.txt" files and then run this py code.

**Comment by mingyue2108** [comment]
Thank you for answering.
I encountered this error while running the script:



These are the contents of the generated info txt files:

[https://ibb.co/Gd4JXc5](url)

**Comment by HIllya51** [comment]
I can't understand.

**Comment by HIllya51** [comment]
this is only use to show chinese charactors. if you dont't use chinese, you can ignore it and drawfont.

**Comment by mingyue2108** [comment]
I tried it but got an error. The generated fonts repeat the headers, while others remain unchanged.
![Screenshot 2024-01-02 173436](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/137147945/18a359e2-3e92-4f19-b822-9d5b5cb4e3ff)

**Comment by HIllya51** [comment]
are you chinese?

**Comment by mingyue2108** [comment]
我不是中国人，但我能听懂一点中文。

**Comment by HIllya51** [comment]
actually my english is very poor, so i really can't understand what's you meaning...

**Comment by HIllya51** [comment]
> I tried it but got an error. The generated fonts have duplicated headers, while others remain unchanged. ![Screenshot 2024-01-02 173436](https://private-user-images.githubusercontent.com/137147945/293673785-18a359e2-3e92-4f19-b822-9d5b5cb4e3ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQwODIsIm5iZiI6MTcwNDE5Mzc4MiwicGF0aCI6Ii8xMzcxNDc5NDUvMjkzNjczNzg1LTE4YTM1OWUyLTNlOTItNGYxOS1iODIyLTlkNWI1Y2I0ZTNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTFmN2Y0MjI3ZDNhNjVjYWUzYWY0YjA1ZjkyODY3N2I3MzJhZjQ5YWUyNDlhMjEyYTgzOTRhNTlmYjIwOWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y_8nA4lDoelUkbD9JZ9hoAS6L4T3uURi0zPoihJmVKk)
> 
> The left one is the new font generated by drawfont.py, and the right one is the original. ![image](https://private-user-images.githubusercontent.com/137147945/293674103-e841748f-4d9b-45ae-925b-333c28688121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQwODIsIm5iZiI6MTcwNDE5Mzc4MiwicGF0aCI6Ii8xMzcxNDc5NDUvMjkzNjc0MTAzLWU4NDE3NDhmLTRkOWItNDVhZS05MjViLTMzM2MyODY4ODEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWQ1MjA4NmYzNzUwODZmMGY3NWYzNmE2OWUxZmE1ZjZlMGM2MWZjN2UxYzllNmYwOWRjYzg3MTE5NTdhZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DeE02fU077__quMYIOSygd0VWXYq4HojthRLCrK8qXY)

how do you get these two file? i find all files in my directory and cant find any one like these

**Comment by HIllya51** [comment]
what is "duplicated headers"?

**Comment by HIllya51** [comment]
why the left file contains "CZ2" at 0x44E？
"CZ2" is magic of image format, i can't understand why it can apply at the middle of the file.

**Comment by mingyue2108** [comment]
> > I tried it but got an error. The generated fonts have duplicated headers, while others remain unchanged. ![Screenshot 2024-01-02 173436](https://private-user-images.githubusercontent.com/137147945/293673785-18a359e2-3e92-4f19-b822-9d5b5cb4e3ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQwODIsIm5iZiI6MTcwNDE5Mzc4MiwicGF0aCI6Ii8xMzcxNDc5NDUvMjkzNjczNzg1LTE4YTM1OWUyLTNlOTItNGYxOS1iODIyLTlkNWI1Y2I0ZTNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTFmN2Y0MjI3ZDNhNjVjYWUzYWY0YjA1ZjkyODY3N2I3MzJhZjQ5YWUyNDlhMjEyYTgzOTRhNTlmYjIwOWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y_8nA4lDoelUkbD9JZ9hoAS6L4T3uURi0zPoihJmVKk)
> > The left one is the new font generated by drawfont.py, and the right one is the original. ![image](https://private-user-images.githubusercontent.com/137147945/293674103-e841748f-4d9b-45ae-925b-333c28688121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTQwODIsIm5iZiI6MTcwNDE5Mzc4MiwicGF0aCI6Ii8xMzcxNDc5NDUvMjkzNjc0MTAzLWU4NDE3NDhmLTRkOWItNDVhZS05MjViLTMzM2MyODY4ODEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMTA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWQ1MjA4NmYzNzUwODZmMGY3NWYzNmE2OWUxZmE1ZjZlMGM2MWZjN2UxYzllNmYwOWRjYzg3MTE5NTdhZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DeE02fU077__quMYIOSygd0VWXYq4HojthRLCrK8qXY)
> 
> how do you get these two file? i find all files in my directory and cant find any one like these

[https://github.com/HIllya51/Cartagra_FHD_CHS/blob/d18d2098b555639718dc5c47301f8cfafb557ceb/font/drawfont.py#L90](url)
I placed the original font obtained from another game in the -s "C:\InnocentGrey\カルタグラ FHD\files\FONT\", and then ran the code to generate a new font in -o "C:\InnocentGrey\カルタグラ FHD\files\FONT_NEW\". The left one which has cz2 magic header in the middle of the file is the new font

**Comment by HIllya51** [comment]
cz2 is the head of file, it can't present at the middle of file. so i really can't understand.
