### ISSUE TITLE
CZ4图像

### ISSUE THREAD

**Issue by Leticiel** [HIllya51/Cartagra_FHD_CHS#18]
请问您能告诉我如何提取CZ4图像吗？谢谢。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/Cartagra_FHD_CHS/blob/main/image/czximage/cz2image.cpp

**Comment by HIllya51** [comment]
不对，我操，我搞错了，提前代码我给删了

**Comment by HIllya51** [comment]
吓我一跳，找到备份了，等下

**Comment by HIllya51** [comment]
[CZXImage.zip](https://github.com/HIllya51/Cartagra_FHD_CHS/files/13858268/CZXImage.zip)

**Comment by Leticiel** [comment]
谢谢。

**Comment by Leticiel** [comment]
我在运行pakimage_png2cz.py时遇到了这个错误。请问您能提供一下您的image2cz.exe吗？非常感谢。
![Screenshot 2024-01-09 111339](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/b2599c2b-d54a-435b-9cf4-af70f2fb916c)

**Comment by HIllya51** [comment]
[image2cz.zip](https://github.com/HIllya51/Cartagra_FHD_CHS/files/13869614/image2cz.zip)

**Comment by staciaa123** [comment]
你知道怎样把竖排文本转换成横排吗？因为我想把游戏翻译成英文。

**Comment by HIllya51** [comment]
啥意思？没懂

**Comment by Leticiel** [comment]
我是想问，将文本转为横向排列是否可行？
![Screenshot 2024-01-09 154723](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/5fe2ae1a-c281-41da-9c5e-93277c5aed18)

**Comment by HIllya51** [comment]
不知道哦，不过你可以研究一下FONT_V，大概你把字体画成这样的就行了吧

**Comment by Leticiel** [comment]
请问您能提供带有CZ3功能的image2cz.exe的新版本吗？非常感谢。

**Comment by HIllya51** [comment]
[image2cz.zip](https://github.com/HIllya51/Cartagra_FHD_CHS/files/13997600/image2cz.zip)

**Comment by Leticiel** [comment]
我在运行被注入了CHSpatch.dll的可执行文件时遇到了这个错误。
![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/e1595771-43ed-48d4-9ad4-59a4b39d20e5)

**Comment by HIllya51** [comment]
[恋狱～月狂病～.zip](https://github.com/HIllya51/Cartagra_FHD_CHS/files/14066258/default.zip)
我直接添加导入表弄得，没有弄注入

**Comment by staciaa123** [comment]
非常感谢。
为什么我不能更改角色名称，除了Yura之外？

![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/9a17060f-5504-4aac-ba3e-4d136f116f57)

![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/534834aa-6126-44c0-9cb0-828f5fcc1085)

**Comment by Leticiel** [comment]
可以在不出错的情况下添加超过原始字符串长度的字符串吗？

![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/e0552339-89c3-4965-a610-05fa49fa3cde)

![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/f283b734-8758-4823-9c38-9e3acb9223d8)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/Cartagra_FHD_CHS/blob/3af9f216d93f021ec92f2af9f708595f3273b7d3/uitext.txt#L304
https://github.com/HIllya51/Cartagra_FHD_CHS/blob/3af9f216d93f021ec92f2af9f708595f3273b7d3/uitext.txt#L295
找一处没有用足够长的文本，然后把原本设为空，没用的那行改成目标翻译
然后 https://github.com/HIllya51/Cartagra_FHD_CHS/blob/3af9f216d93f021ec92f2af9f708595f3273b7d3/patch/patch.cpp#L437 添加一个VirtualProtect，其中，“0x400030-0x3FFF20“在uitext.txt里有，0x2A1261你可以用CE搜原文字符串的偏移地址。

**Comment by Leticiel** [comment]
非常感谢

**Comment by Leticiel** [comment]
可以问一下如何翻译这些选项吗？即使我已经翻译过它们，它们仍然是日语。

![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/853551e5-b277-43e0-9b0d-fc1ae4cb4999)

![image](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/155957757/7a56b93d-830e-43c3-b861-8b6d5ac60f34)

我可以使用LuckSystem工具翻译它们，但是如果翻译后的字符串长度不等于原始字符串的长度，游戏将会崩溃。

**Comment by HIllya51** [comment]
不知道，我没用这个翻译

**Comment by Leticiel** [comment]
请问你能给我 image2cz.exe 吗？我的文件出了些问题，无法正常工作。谢谢！
