### ISSUE TITLE
萌新求助

### ISSUE THREAD

**Issue by Y2ark** [HIllya51/Cartagra_FHD_CHS#27]
文件压缩包是下载下来了，恋狱FHD也有了，但这个怎么用啊

**Comment by HIllya51** [comment]
这是我们的汉化项目，目前还在校对中，如果你会程序那么可以偷跑，不会那还是先等会儿吧。

**Comment by Y2ark** [comment]
> 这是我们的汉化项目，目前还在校对中，如果你会程序那么可以偷跑，不会那还是先等会儿吧。

汉化组的大佬们辛苦了，加油
