### ISSUE TITLE
感谢贵组的汉化工作

### ISSUE THREAD

**Issue by ShizukuAya** [HIllya51/Cartagra_FHD_CHS#28]
最近在推此作，有幸看到贵组的汉化，省去我不少查词的时间。但我在参照贵组文本进行阅读的时候，发现还是有不少错字、误译之处，于是就fork了一下，边看边做了一些自己能力范围内的改正，如有错误，还请海涵。目前改了0218-02，之后我继续推进剧情也会继续下去的，希望能为贵组的工作做一点小贡献。

**Comment by HIllya51** [comment]
我们已经在二校了，文本没有更新到github上。如果有参与的打算，不要在这个文本上修改，这都是初翻的文本。。。

**Comment by HIllya51** [comment]
你可以把QQ给我

**Comment by ShizukuAya** [comment]
> 你可以把QQ给我

656270916

**Comment by HIllya51** [comment]
OK
