### ISSUE TITLE
错字和格式乱码

### ISSUE THREAD

**Issue by SunXiaocuan257** [HIllya51/Cartagra_FHD_CHS#29]
大佬根据你的代码库硬猜出来解包pak后用pycharm运行了代码把新打包替换后出现了两种情况，错字或者格式乱码
这个补丁到底怎么用

**Comment by HIllya51** [comment]
这个需要c++编译，很麻烦的

**Comment by HIllya51** [comment]
这个只是初翻，我们快二校完了，即使成功运行也请不要散布
