### ISSUE TITLE
关于字体的问题

### ISSUE THREAD

**Issue by Fujiteng** [HIllya51/Cartagra_FHD_CHS#30]
![QQ截图20240502104912](https://github.com/HIllya51/Cartagra_FHD_CHS/assets/168698241/3ee3998b-e8a9-4dc9-8d75-99811636db79)

和效果图中不一样，我替换后似乎缺少字体。设置中能改的只有几个日本字体。不知道怎么换成中文

**Comment by HIllya51** [comment]
https://github.com/HIllya51/Cartagra_FHD_CHS/issues/29
