### ISSUE TITLE
文本版本问题

### ISSUE THREAD

**Issue by Cecropis** [HIllya51/Cartagra_FHD_CHS#33]
群里有人说似乎放出来的补丁中，文本为一校文本而非二校文本，请问是否属实？
不知道能否联系上群主。

**Comment by HIllya51** [comment]
我也联系不上群主。但补丁的文本是最新的，github因为担心IG吧可能会抄袭，所有后面没有更新。

**Comment by Cecropis** [comment]
补丁没问题就好
![0fbbd745ef2b7823130b7d854d92048b](https://github.com/user-attachments/assets/44d7d3b3-fb00-47a4-8653-6931f411065e)

**Comment by HIllya51** [comment]
至少我这个release的肯定是正确了，群主的链接里的你测一下看看有没有搞错吧，我百度账号没了下载不了

**Comment by HIllya51** [comment]
咦，好像也不太对

**Comment by HIllya51** [comment]
群主最后给我的文本好像给错了

**Comment by Cecropis** [comment]
那要先发个补丁修正一下吗？还是先找到群主再说?

**Comment by HIllya51** [comment]
我这没最新的文本……

**Comment by Cecropis** [comment]
啊这，那只能等群主回复了。。。

**Comment by HIllya51** [comment]
我用群主发给我的把之前的给覆盖掉了。。。不知道群主那里什么情况。。。不然真要难绷了

**Comment by Cecropis** [comment]
要不先找几个二校把文本先整理一下

**Comment by HIllya51** [comment]
我找到新的文本了
